// Re-export all API types from shared package (single source of truth)
export type {
  PerkType,
  MerchantPerk,
  CustomerPerkView,
  MerchantLocation,
  MerchantResponse,
  CustomerResponse,
  MerchantScopedCustomerResponse,
  CustomerEnrollment,
  TransactionResponse,
  MerchantStatsResponse,
  RecordPurchaseResponse,
  RedeemPointsResponse,
  PaginatedResponse,
  AnalyticsDataPoint,
  AnalyticsData,
  CampaignResponse,
  CampaignType,
  TierBreakdownResponse,
  CustomerInsights,
  PerkInsights,
  WebhookConfigResponse,
} from '@pointly/shared';
